spring.application.name=land-connect-backend
spring.datasource.url=jdbc:mysql://localhost:3306/land_connect_db
spring.datasource.username=root
spring.datasource.password=govind18500
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# JWT Configuration
jwt.secret=ReplaceThisWithASecretKeyThatIsAtLeast32CharactersLong123456
jwt.expiration=86400000
#  86400000 = 24 hours in milliseconds.

# =========================
# Email Configuration
# =========================

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=govindkumar35322@gmail.com
# govindkumar35322@gmail.com
spring.mail.password=pzdjnacsgcnjrapg
#Govind@18500
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

#spring.jpa.properties.hibernate.format_sql=true
#spring.jpa.open-in-view=false

# ===============================
# Logging
# ===============================
#logging.level.org.springframework.security=INFO
l ogging.level.org.hibernate.SQL=DEBUG
#logging.level.org.hibernate.orm.jdbc.bind=TRACE
